<a href="https://colab.research.google.com/github/AndresBeta123/CoreWCF/blob/main/Sumador/Prueba1Sumador1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# TensorFlow y tf.keras
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import random

# Librerias de ayuda
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.8.2


Creando datos

In [ ]:
A = []
S = []

for i in range(30000):
  x = random.randint(0, 200)
  y = random.randint(0, 200)
  c = x+y
  x = [int(i) for i in str(bin(x))[2:]]
  x = [0 for i in range(8-len(x))]+x
  y = [int(i) for i in str(bin(y))[2:]]
  y = [0 for i in range(8-len(y))]+y

  c = [int(i) for i in str(bin(c))[2:]]
  c = [0 for i in range(9-len(c))]+c
  A.append([x,y])
  S.append(c)
A = np.array(A)
S = np.array(S)

In [ ]:
activ = 'elu'
model = keras.Sequential([
        keras.layers.Flatten(input_shape=(2, 8)),
    keras.layers.Dense(32, activation=activ),
    keras.layers.Dense(32, activation=activ),
    keras.layers.Dense(18, activation=activ),
    keras.layers.Dense(9, activation=activ)
])

In [ ]:
model.compile(optimizer='adam',
              loss='binary_focal_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_18 (Flatten)        (None, 16)                0         
                                                                 
 dense_73 (Dense)            (None, 32)                544       
                                                                 
 dense_74 (Dense)            (None, 32)                1056      
                                                                 
 dense_75 (Dense)            (None, 18)                594       
                                                                 
 dense_76 (Dense)            (None, 9)                 171       
                                                                 
Total params: 2,365
Trainable params: 2,365
Non-trainable params: 0
_________________________________________________________________


Entrenando el sistema

In [ ]:
model.fit(A,S,epochs=15)

Epoch 1/15
938/938 [==============================] - 3s 3ms/step - loss: 0.3343 - accuracy: 0.1463
Epoch 2/15
938/938 [==============================] - 2s 2ms/step - loss: 0.1704 - accuracy: 0.2284
Epoch 3/15
938/938 [==============================] - 2s 2ms/step - loss: 0.1632 - accuracy: 0.3051
Epoch 4/15
938/938 [==============================] - 2s 2ms/step - loss: 0.1576 - accuracy: 0.3509
Epoch 5/15
938/938 [==============================] - 2s 2ms/step - loss: 0.1483 - accuracy: 0.3685
Epoch 6/15
938/938 [==============================] - 2s 2ms/step - loss: 0.1355 - accuracy: 0.3560
Epoch 7/15
938/938 [==============================] - 2s 3ms/step - loss: 0.1302 - accuracy: 0.4336
Epoch 8/15
938/938 [==============================] - 2s 3ms/step - loss: 0.1289 - accuracy: 0.4698
Epoch 9/15
938/938 [==============================] - 2s 2ms/step - loss: 0.1243 - accuracy: 0.4867
Epoch 10/15
938/938 [==============================] - 2s 2ms/step - loss: 0.1206 - accuracy: 0.4979

prediccion

In [ ]:
tA = []
tS = []

for i in range(10):
  x = random.randint(0, 200)
  y = random.randint(0, 200)
  c = x+y
  x = [int(i) for i in str(bin(x))[2:]]
  x = [0 for i in range(8-len(x))]+x
  y = [int(i) for i in str(bin(y))[2:]]
  y = [0 for i in range(8-len(y))]+y

  c = [int(i) for i in str(bin(c))[2:]]
  c = [0 for i in range(9-len(c))]+c
  tA.append([x,y])
  tS.append(c)
tA = np.array(tA)
tS = np.array(tS)

In [ ]:
for i in range(10):
  print("test entrada: ",tA[i])
  print("test salida correcta: ",tS[i])
  predictions = model.predict(tA)
  nP = []
  print(predictions[i])
  for a in predictions[i]:
    if(a>0.5):
      nP.append(1)
    else:
      nP.append(0)
  print("salida ia: ",nP)
  print("----------------")


test entrada:  [[1 1 0 0 0 0 1 0]
 [0 1 0 1 1 0 0 1]]
test salida correcta:  [1 0 0 0 1 1 0 1 1]
[0.9008269  0.44780913 0.5117555  0.4885047  0.50656635 0.4999682
 0.50290763 0.9546747  1.5512707 ]
salida ia:  [1, 0, 1, 0, 1, 0, 1, 1, 1]
----------------
test entrada:  [[0 1 0 0 1 0 1 1]
 [1 0 1 1 1 0 1 1]]
test salida correcta:  [1 0 0 0 0 0 1 1 0]
[ 0.55308735  0.5385452   0.55841035  0.54574627  0.48606825  0.48504886
  0.4767653   0.9274628  -0.12227976]
salida ia:  [1, 1, 1, 1, 0, 0, 0, 1, 0]
----------------
test entrada:  [[0 1 1 1 1 0 1 0]
 [0 1 1 1 1 0 0 1]]
test salida correcta:  [0 1 1 1 1 0 0 1 1]
[0.27734876 0.5359996  0.34031045 0.523612   0.51431084 0.49608436
 0.508018   1.0089241  1.3626546 ]
salida ia:  [0, 1, 0, 1, 1, 0, 1, 1, 1]
----------------
test entrada:  [[0 0 1 1 0 0 1 1]
 [1 0 1 1 1 1 0 0]]
test salida correcta:  [0 1 1 1 0 1 1 1 1]
[0.04431286 0.6159042  0.57535756 0.54382765 0.51045996 0.4738188
 0.50538987 1.063493   1.268895  ]
salida ia:  [0, 1, 1, 1, 1